### PR TITLE
feat: Add offline search

### LINKED ISSUE #115: [Task] Add an offline search feature
## What should be done 
Add the offline search feature.
- We want to add a search bar in every page of the doc (header) to search in it.
- The search should work offline if possible.
- Try to mimic the Elixir example for the list under the input + the search page result.
- The page show a line or two of the full text where the result is found AND the link of this page + anchor (see elixir page example)

## Technical recommandation
A lib that should be capable of such feature : https://lunrjs.com/
An example of a search that actually uses this lib : https://hexdocs.pm/elixir

## Ecological concerns
The offline feature is important to limit the data usage in general.

### PR DESCRIPTION
**Pull request by taorepoara**
Closes #115 

## Description of the changes
In order to make it easier to find what you're looking for in the documentation, I've added a search form.

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [x] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

## Technical highlight/advice
I've used the Lunr.js search engine. The search index is generated during the Nginx website generation and it's based on the previously generated HTML pages. 

In order to display the search results we need to have the target page content. I load this content when the page is in the results (and not previously loaded).

For this first implementation this only work for the Nginx target (the production one). It would have been much less efficient to handle for the Express target since we would have to regerate the search index at every page load which needs to rendre every HTML pages.

### CODE REVIEW

**Comment by taorepoara** [comment]
I also added some HTML and CSS fixes that I did not saw earlier

**Comment by taorepoara** [comment]
For now the search engine is not really offline since load Lunr.js from unpkg.com.

I think that for now it's better for cache management, but we'll have to improve it if we want to make it downloadable locally.

**Comment by jonas-martinez** [comment]
@taorepoara I can't make the search system work on my computer. Maybe something needs to be run before ? If so, please add the commands to the README.

**Review by jonas-martinez — CHANGES_REQUESTED** [review]
See my comment above

**Comment by taorepoara** [comment]
@jonas-martinez Have you tried with the Nginx target ?  
 

The `npm start` way wont work, you'll have to do `npm run build` and then build and run the Dockerfile.

**Comment by jonas-martinez** [comment]
@taorepoara It stays stuck in the "Starting NGINX" step. I have run the npm run build so I don't understand what I'm missing.
image

**Comment by taorepoara** [comment]
> @taorepoara It stays stuck in the "Starting NGINX" step. I have run the npm run build so I don't understand what I'm missing. image

Have you try to go to https://localhost:8080 after that ?

I'll had more explanation in the doc

**Comment by jonas-martinez** [comment]
@taorepoara Yes, it doesn't work even when exposing the port 8080.

**Comment by taorepoara** [comment]
@jonas-martinez It might be due to the macOS config. We'll have to debug it together

**Review by jonas-martinez — APPROVED** [review]

**Pull request merged**
