### PR TITLE
feat: Crons

### PR DESCRIPTION
**Pull request by jonas-martinez**
Closes # 

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

### CODE REVIEW

**Comment by taorepoara** [comment]
This project is a doc project so the commit type should not be `docs` (unless you document the project it self, like editing the README).

**Comment by taorepoara** [comment]
This to technical. We will have a specific part in the references to describe the API, but here you should describe at least one use case I think

**Comment by jonas-martinez** [comment]
@taorepoara I did some changes so that it is less technical about the API. I added some documentation about how the 5 star cron format works (* * * * *).

**Review by taorepoara — APPROVED** [review]

**Pull request merged**
